language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_deploy:
- npm run-script update-repos && npm run-script build
deploy:
  provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist